### ISSUE TITLE
Make Duplicate Action less prominent 

### ISSUE THREAD

**Issue by regisphilibert** [sanity-io/document-internationalization#106]
I enabled the localization on a schema, and now the Actions look like this: 

![Capture d’écran, le 2023-02-14 à 16 42 00](https://user-images.githubusercontent.com/1480503/218869739-6f13cef7-b011-4c0c-9102-3c7acdb85391.png)

I think editors will want to retain the "Publish" button as the main action, and leave the rarely used "Duplicate (including translation)" button in the drop down...

Any way to change this default behaviour through the config?

Thanks!

**Comment by thijs-justacodename** [comment]
I had the same issue when I had the equivalent of the following in sanity.config:
```
plugins: [
  documentI18n({ includeDeskTool: false, ...otherI18nOptions}),
  deskTool(),
  ...otherPlugins
],
```
It helped me to use:
```
plugins: withDocumentI18nPlugin([ deskTool(), ...otherPlugins], {
  includeDeskTool: false, 
  ...otherI18nOptions
}
```
because that way the DocumentActions actually get added properly.
