### ISSUE TITLE
Allow the same slug for translation

### ISSUE THREAD

**Issue by kapyar** [sanity-io/document-internationalization#111]
Hi, I am trying to use sanity and NextJS, and I faced a problem. NextJS support supports postfix localization. So the question is how can I use the nextJS localization pattern `https://example.com/es/about -> https://example.com/pl/about `, `about` is a value that I got from _sanity slug_. When I created the localization of content I got an error that slug must be unique. 

Is it possible to hide the slug for translation? Or should I use `string` instead of `slug`?

**Comment by kapyar** [comment]
solved it `"slug":  coalesce(__i18n_base->slug, slug)`

**Comment by kapyar** [comment]
> How and where did you implement this exactly? And are you using Sanity Studio v3 or v2?
I modify my query so it select always base `slug`
here the example of my query

`` const query = `*[_type == "track" && __i18n_lang=='${locale}' 
  && references(*[_type == "ganre" && __i18n_lang=='${locale}' 
  && coalesce(__i18n_base->slug, slug).current=="${params.genre}"]._id)]
  {``

**Comment by benjick** [comment]
How is that possible? It keeps telling me the slug is a duplicate in Sanity studio

**Comment by kapyar** [comment]
> How is that possible? It keeps telling me the slug is a duplicate in Sanity studio

Correct, on localizaed document the slug must be different, the query that I posted always select base language slug

**Comment by lauradecc** [comment]
> > How and where did you implement this exactly? And are you using Sanity Studio v3 or v2?
> 
> I modify my query so it select always base `slug` here the example of my query
> 
> `` const query = `*[_type == "track" && __i18n_lang=='${locale}' && references(*[_type == "ganre" && __i18n_lang=='${locale}' && coalesce(__i18n_base->slug, slug).current=="${params.genre}"]._id)] { ``

Could you explain more how to do it? I don't quite understand how to solve the problem.

Thank you!
