### ISSUE TITLE
Swedish language displays wrong flag.

### ISSUE THREAD

**Issue by erikjoelGP** [sanity-io/document-internationalization#121]
![Screenshot 2023-04-25 at 11 09 42](https://user-images.githubusercontent.com/85553733/234230041-e876cc9d-1140-425a-8f63-d98f3f15626e.png)

**Comment by grizzm0** [comment]
Using  `sv-SE` instead of just `sv` solves the problem. But yeah, `sv` should probably map to Sweden as well.
