### ISSUE TITLE
Support styled-components 6.1.1.

### ISSUE THREAD

**Issue by mdillgen** [sanity-io/document-internationalization#167]
As of now, the plugin requires styled-components@"^5.3.6". So it’s hard to use in conjunction with e.g. sanity-presentation, which requires "styled-components": "6.1.1"
<img width="590" alt="image" src="https://github.com/sanity-io/document-internationalization/assets/9297500/35715163-5924-4bea-9e22-16931a889d07">

**Comment by viswongdev** [comment]
Any solutions?
