### ISSUE TITLE
Remove from default listItem doesn't work with Structure.getFilteredDocumentTypeListItems()

### ISSUE THREAD

**Issue by JeremDigi** [sanity-io/document-internationalization#23]
Hello,

I'm trying to implement the plugin in my own structure.

```js
// deskStructure.js
import S from "@sanity/desk-tool/structure-builder";
import * as Structure from "@sanity/document-internationalization/lib/structure";
import { IoNewspaperOutline, IoDocumentTextOutline, IoGitMergeOutline } from "react-icons/io5";

// For document-internationalization
export const getDefaultDocumentNode = (props) => {
  if (props.schemaType === 'myschema') {
    return S.document().views(Structure.getDocumentNodeViewsForSchemaType(props.schemaType))
  }
  return S.document()
}

export default () =>  {

  // For document-internationalization
  const langStructure = Structure.getFilteredDocumentTypeListItems();

  return S.list()
    .title("Contenu")
    .items([
      S.listItem()
        .title("Blog")
        .icon(IoNewspaperOutline)
        .child(
          S.list()
            // Sets a title for our new list
            .title("Éléments du blog")
            .items([
              S.listItem().title("Articles").icon(IoDocumentTextOutline).child(
                S.documentList()
                  .title("Tous les articles")
                  .filter('_type == "post"')
                // S.document().schemaType("post").documentId("post")
              ),
              S.listItem().title("Catégories").icon(IoGitMergeOutline).child(
                S.documentList()
                  .title("Toutes les catégories")
                  .filter('_type == "category"')
              ),
            ])
        ),
      ...langStructure,
      // Remove from default ListItems
      ...S.documentTypeListItems().filter(
        (listItem) => !["post", "category"].includes(listItem.getId())
      )
    ]);
}
```

When I do this, the "post" and "category" items are added to `listItem` while I ask to remove them (it's ignored).

<img width="708" alt="sanity-structure-bug" src="https://user-images.githubusercontent.com/33928345/153758756-0229e3f2-427d-4919-acaa-f0117f0c3c6f.png">

Thank you

**Comment by JeremDigi** [comment]
Also, with my custom structure, when I go to `Blog`->`Articles` I see all the articles mixed up (in French and in English). And I don't have access to the translations panel.

<img width="1387" alt="Capture d’écran 2022-02-13 à 16 13 19" src="https://user-images.githubusercontent.com/33928345/153759745-529ef3e7-e0f9-4f81-9884-c368432ff421.png">

But when I go directly to the auto-generated item `Articles`, everything works normally. Why?

<img width="1060" alt="Capture d’écran 2022-02-13 à 16 14 23" src="https://user-images.githubusercontent.com/33928345/153759796-719b29cf-a540-4118-8151-c497b5a842d8.png">

**Comment by iksi** [comment]
@JeremDigi It seems that you need to use the document list items that come from `getFilteredDocumentTypeListItems()`. So in your case you would need to use:

```js
.title("Éléments du blog")
.items([
    listItems.find(({ id }) => {
        return id === 'post';
    }),
    listItems.find(({ id }) => {
        return id === 'category';
    }),
])
```

However you would need to find another way however to change the title and the icon (if you don’t want to do this on the schema).

**Comment by SimeonGriggs** [comment]
Closing this issue as the desk items are no longer exported by the plugin – since it no longer needs to customise your View Panes.
