### ISSUE TITLE
Language Codes based on the ISO Standard 

### ISSUE THREAD

**Issue by astrit** [sanity-io/document-internationalization#57]
While setting up Swedish documents I expected the code "sv" to show the Swedish flag in the desk, but it shows the El Salvador which is a bit confusing. I managed to get the Swedish flag with the code "se", which in the ISO standard is Sami.

Maybe a different standard is used, but in case this is a mistake I thought I would bring it up.

As reference - the [ISO Standard 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)

**Comment by perjonsson** [comment]
Did you try `sv-SE`? In the example for v3, both language and country is specified: https://github.com/sanity-io/document-internationalization/blob/v3/docs/enabling-and-configuring.md#complete-example

**Comment by LiamMartens** [comment]
@astrit as @perjonsson eludes to, when detecting the flags we are expecting the input to be a language and culture combination and flags are displayed using their emoji equivalents; thus in the case of Sweden this is SE
