### ISSUE TITLE
Installing alongside newer versions of react-router fails (old, unused dependency in this repo)

### ISSUE THREAD

**Issue by lasseaeggen** [sanity-io/document-internationalization#88]
When installing alongside newer versions of `react-router` (`v6`), the installation fails due to a conflicting peer dependency.

`npm install --save @sanity/document-internationalization` gives the following output:
```
npm ERR! Could not resolve dependency:
npm ERR! @sanity/document-internationalization@"*" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react-router@5.3.4
npm ERR! node_modules/react-router
npm ERR!   peer react-router@"^5.0.0" from @sanity/document-internationalization@1.0.2
npm ERR!   node_modules/@sanity/document-internationalization
npm ERR!     @sanity/document-internationalization@"*" from the root project
```

A quick search in github reveals no usage of `react-router` in the `document-i18n` package. A possible solution is removing dependencies from the `package.json` to clean up the deps.

**Comment by keboye** [comment]
Same problem.

**Comment by nilsborg** [comment]
Me too...

**Comment by EmilEinarsen** [comment]
Same problem. Just tried to migrating v2 to v3 in my Remix project. This peer dependency made the whole app crash

**Comment by nilsborg** [comment]
Any updates on this one?

**Comment by LiamMartens** [comment]
As a workaround you can probably add a react-router resolution to v6.
We'll remove the v5 dependency in the future.

I did notice this appears to be working in V3 with the latest version anyways
